### ISSUE TITLE
Add zenodo citation

### ISSUE THREAD

**Issue by lgatto** [cvanderaa/EuroBioc2019-Poster#1]
Once you have uploaded your poster on zenodo and have your citation/DOI, add it to your README.md file. (See [here](https://github.com/UCLouvain-CBIO/2019_12_09_EuroBioc_Bxl/blob/master/README.md) for an example).

**Comment by cvanderaa** [comment]
Done ! 
See this [commit](https://github.com/cvanderaa/EuroBioc2019-Poster/commit/c10e96e9bc7b0594908988c500af7c0db0f01d6e)
